#Github Actions
name: My First Github Actions
on: push
jobs:
  build:
    runs on: ubuntu-latest

    strategy:
      matrix:
        pthon-version: [3.8,3.9]

    steps:
    -uses: actions/checkout@v3                     #checking out versions
    -name: setup python
     uses: actions/setup-python@v2
     with:
       python-version: ${{matrix.python-version}}

    -name: Install dependencies
     run: |
       python -m pip install --upgrade pip
       pip install pytest

    -name: Runtests
     run: |
       cd src
       python -m pytest addition.py
    
